apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hybridscalers.autoscaling.custom
spec:
  group: autoscaling.custom
  names:
    kind: HybridScaler
    singular: hybridscaler
    plural: hybridscalers
    shortNames: [hs]
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                scaleTargetRef:
                  type: object
                  properties:
                    kind: 
                      type: string
                    name:
                      type: string
                    apiVersion:
                      type:
                        string
                minReplicas:
                  type: integer
                  format: int32
                maxReplicas:
                  type: integer
                  format: int32
                resourcePolicy:
                  type: object
