# permissions for end users to view hybridscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hybridscaler-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hybrid-scaler
    app.kubernetes.io/part-of: hybrid-scaler
    app.kubernetes.io/managed-by: kustomize
  name: hybridscaler-viewer-role
rules:
- apiGroups:
  - scaling.autoscaling.custom
  resources:
  - hybridscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scaling.autoscaling.custom
  resources:
  - hybridscalers/status
  verbs:
  - get
