---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - scaling.autoscaling.custom
  resources:
  - hybridscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.autoscaling.custom
  resources:
  - hybridscalers/finalizers
  verbs:
  - update
- apiGroups:
  - scaling.autoscaling.custom
  resources:
  - hybridscalers/status
  verbs:
  - get
  - patch
  - update
